site_name: ZJUSCT
site_url: https://docs.zjusct.io/
repo_name: docs.zjusct.io
repo_url: https://github.com/ZJUSCT/docs.zjusct.io
edit_uri: blob/main/docs/
site_description: ZJUSCT
site_author: ZJUSCT
copyright: ZJUSCT

nav:
  # å·²å¯ç”¨ include_dir_to_nav æ’ä»¶ï¼Œå¯ä½¿ç”¨ç›®å½•åæ·»åŠ è¯¥ç›®å½•ä¸‹æ‰€æœ‰æ–‡ä»¶
  # æ–‡ä»¶æŒ‰å­—æ¯åºæ’åˆ—ï¼Œå¦‚æœåŒçº§æœ‰å…¶ä»–æ–‡ä»¶ï¼Œå°±éœ€è¦ä¸“é—¨æŠŠ index.md æ”¾åœ¨æœ€å‰é¢
  - é¦–é¡µ: index.md
  - æ–‡æ¡£æŒ‡å¼•:
    - guideline/index.md
    - guideline
  - ğŸ† ç«èµ›: competition
  - ğŸ¦… Falcon:
    - falcon/index.md
    - falcon
  - ğŸ”§ ä¼˜åŒ–:
    - optimization/index.md
    - å¹¶è¡Œç¼–ç¨‹: optimization/parallel
    - é«˜æ€§èƒ½ç½‘ç»œ: optimization/HPN
  - âš™ï¸ è¿ç»´: operation
  - âœï¸ åšå®¢: blog


theme:
  name: material
  custom_dir: overrides
  logo: assets/zjusct.svg
  favicon: assets/zjusct.png
  palette:
    - media: "(prefers-color-scheme)"
      primary: black
      toggle:
        icon: material/brightness-auto
        name: åˆ‡æ¢è‡³æµ…è‰²æ¨¡å¼
    - media: "(prefers-color-scheme: light)"
      scheme: zjusct
      toggle:
        icon: material/brightness-7
        name: åˆ‡æ¢è‡³æ·±è‰²æ¨¡å¼
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: æ ¹æ®ç³»ç»Ÿæ¨¡å¼åˆ‡æ¢ä¸»é¢˜
  features:
    # ä»£ç å—æ“ä½œ
    - content.code.copy
    - content.code.select
    - content.code.annotate
    # åº•éƒ¨å¯¼èˆª
    - navigation.footer
    # é¡¶éƒ¨å¯¼èˆª
    - navigation.tabs
    # ä¾§è¾¹æ æŒ‰ section å±•å¼€
    - navigation.sections
    - navigation.expand
    # ç« èŠ‚é¦–é¡µ index.md
    - navigation.indexes
    # é”šç‚¹
    - navigation.tracking
    # è·¯å¾„
    - navigation.path
    # å›åˆ°é¡¶éƒ¨
    - navigation.top
    - toc.follow
    # é¡µé¢ç¼–è¾‘
    - content.action.edit
    # æœç´¢
    - search.suggest
    - search.highlight
    - search.share

markdown_extensions:
  # Admonition
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      # Mermaid
      custom_fences:
        - name: mermaid
          class: mermaid
          format:
            !!python/name:pymdownx.superfences.fence_code_format # Code Block
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  # Tab Card
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  # Grid, Image
  - attr_list
  - md_in_html
  # Icon
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg # List
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  # TOC
  - toc:
      permalink: true
      # ä¸­æ–‡é”šç‚¹
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  # MathJax
  - pymdownx.arithmatex:
      generic: true
  # Keys
  - pymdownx.keys
  # Highlight
  - pymdownx.critic
  # æ—¶é—´è½´ã€ç”˜ç‰¹å›¾
  - neoteroi.timeline
  - neoteroi.projects

extra_javascript:
  # MathJax
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/polyfill/index.min.js
  - https://cdn.jsdelivr.net/npm/mathjax/es5/tex-mml-chtml.js
  # Table Sort
  - https://cdn.jsdelivr.net/npm/tablesort/dist/tablesort.min.js
  - javascripts/tablesort.js
  # mermaid
  - https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js

extra_css:
  - stylesheets/fonts.css
  - stylesheets/counter.css
  - stylesheets/theme.css
  # neoteroi
  - stylesheets/neoteroi-v1.1.2.css

plugins:
  - blog
  - git-revision-date-localized:
      enable_creation_date: true
      enable_git_follow: false
  # è¯¥æ’ä»¶æœ¬åœ°ç¼–è¾‘æ—¶å…³é—­ï¼ŒCI æ—¶è‡ªåŠ¨å¼€å¯
  - git-committers:
      enabled: false
      repository: zjusct/docs.zjusct.io
      branch: main
  - glightbox
  - drawio
  - tags
  - search
  - include_dir_to_nav:
      recurse: false
